name: 'book-store-application'
services:
  catalogue-service:
    image: surfergit/bookstore-catalogue-service
    container_name: catalogue-service
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://catalogue-db:5432/postgres
    ports:
      - "8081:8081"
    restart: unless-stopped

    depends_on:
      catalogue-db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: surfergit/bookstore-order-service
    container_name: order-service
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://order-db:5432/postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - CATALOGUE_SERVICE_URL=http://catalogue-service:8081
    ports:
      - "8082:8082"
    restart: unless-stopped

    depends_on:
      order-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 700m