name: 'book-store-application'
services:
  catalogue-service:
    image: surfergit/bookstore-catalogue-service
    container_name: catalogue-service
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://catalogue-db:5432/postgres
    ports:
      - "8081:8081"
    restart: unless-stopped

    depends_on:
      catalogue-db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: surfergit/bookstore-order-service
    container_name: order-service
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://order-db:5432/postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - CATALOGUE_SERVICE_URL=http://api_gateway:8989/catlogue
    ports:
      - "8082:8082"
    restart: unless-stopped

    depends_on:
      order-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 700m

  notification-service:
    image: surfergit/bookstore-notification-service
    container_name: notification-service
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://notification-db:5432/postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    ports:
      - "8083:8083"
    restart: unless-stopped

    depends_on:
      notification-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started

    deploy:
      resources:
        limits:
          memory: 700m

  api_gateway:
    image: surfergit/bookstore-api_gateway
    container_name: api_gateway
    environment:
      - ORDER_SERVICE_URL=http://order-service:8082
      - CATALOGUE_SERVICE_URL=http://catalogue-service:8081
    ports:
      - "8989:8989"
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 700m